stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: normal

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

default:
  image: node:latest
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

# Tests are broken, something to do with this https://github.com/Menci/vite-plugin-wasm/issues/56
# test:
#   stage: build
#   script:
#     - npm run testrun

check_state_migration:
  stage: build
  script:
    - npx --yes ts-json-schema-generator@1.5.0 --path 'src/app/state.ts' --type 'AppPersistentStateUnvalidated' --tsconfig tsconfig.json > data/state/app-state-latest.json
    - npm run format
    - git diff --exit-code

lint:
  stage: build
  script:
    - npm run lint

format:
  stage: build
  script:
    - npm run formatcheck

pages:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  inherit:
    default: false
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - mv dist public
  artifacts:
    paths:
      - public
