// Generates every standalone copy of the app mark from the single source
// artwork in src/components/icons/AppLogoMark.svg.
//
// The source is stroked with `currentColor` so that AppLogo.tsx inherits its
// color from CSS. A favicon or a desktop icon has no CSS to inherit from, so
// this script bakes a color in and hands the result to `tauri icon`, which
// reads SVG directly, to rasterize the platform sizes and containers.
//
// Re-run `npm run icons` after editing the source.

import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

// Matches what's used in the app
const ACCENT_COLOR = "#8e51ff";

// macOS-motivated icon geometry (also used for Windows and Linux)
const CANVAS = 1024;
const TILE = 824;
const TILE_RADIUS = 185;
const MARK = 620;

const root = fileURLToPath(new URL("..", import.meta.url));

const sourcePath = join(root, "src/components/icons/AppLogoMark.svg");
const faviconPath = join(root, "public/icon.svg");

const generatedBanner = (what) =>
  `<!-- ${what}, generated by scripts/generate-icons.mjs. Edit the source mark\n` +
  `     in src/components/icons/AppLogoMark.svg and run \`npm run icons\`. -->\n`;

const source = readFileSync(sourcePath, "utf8");
if (!source.includes("currentColor")) {
  throw new Error(
    `Expected ${sourcePath} to stroke with currentColor. If the mark no longer ` +
      `uses currentColor, this script has nothing to recolor.`,
  );
}

function parseMark(svg) {
  const match = /<svg([^>]*)>([\s\S]*)<\/svg>/.exec(svg);
  if (!match) {
    throw new Error(`Could not find a root <svg> element in ${sourcePath}.`);
  }

  const [, rawAttrs, content] = match;
  const attrs = {};
  for (const attr of rawAttrs.matchAll(/([\w:-]+)\s*=\s*"([^"]*)"/g)) {
    attrs[attr[1]] = attr[2];
  }

  const viewBox = attrs.viewBox?.split(/\s+/).map(Number);
  if (viewBox?.length !== 4) {
    throw new Error(`Expected a viewBox on the root <svg> in ${sourcePath}.`);
  }

  return { attrs, content, viewBox };
}

const { attrs, content, viewBox } = parseMark(source);

writeFileSync(
  faviconPath,
  generatedBanner("Favicon") + source.replaceAll("currentColor", ACCENT_COLOR),
);
console.log(`Wrote ${faviconPath}`);

// Purple background and white stroke
function composeAppIcon() {
  const [minX, minY, vbWidth, vbHeight] = viewBox;
  const scale = MARK / Math.max(vbWidth, vbHeight);
  const offset = (CANVAS - MARK) / 2;

  const inherited = Object.entries(attrs)
    .filter(([name]) => !["width", "height", "viewBox", "xmlns"].includes(name))
    .map(
      ([name, value]) => ` ${name}="${value.replace("currentColor", "#fff")}"`,
    )
    .join("");

  return (
    generatedBanner("Desktop app icon") +
    `<svg width="${CANVAS}" height="${CANVAS}" viewBox="0 0 ${CANVAS} ${CANVAS}" ` +
    `xmlns="http://www.w3.org/2000/svg">` +
    `<rect x="${(CANVAS - TILE) / 2}" y="${(CANVAS - TILE) / 2}" ` +
    `width="${TILE}" height="${TILE}" rx="${TILE_RADIUS}" fill="${ACCENT_COLOR}"/>` +
    `<g transform="translate(${offset - minX * scale} ${offset - minY * scale}) ` +
    `scale(${scale})"${inherited}>${content}</g>` +
    `</svg>\n`
  );
}

const scratch = mkdtempSync(join(tmpdir(), "fluxite-icons-"));
try {
  const appIconPath = join(scratch, "app-icon.svg");
  writeFileSync(appIconPath, composeAppIcon());

  // Default output is src-tauri/icons, resolved next to tauri.conf.json.
  execFileSync("npx", ["--no-install", "tauri", "icon", appIconPath], {
    cwd: root,
    stdio: "inherit",
  });
} finally {
  rmSync(scratch, { recursive: true, force: true });
}

// Remove mobile icons emitted by tauri icon (we only target web/desktop)
for (const mobileDir of ["ios", "android"]) {
  rmSync(join(root, "src-tauri/icons", mobileDir), {
    recursive: true,
    force: true,
  });
}
