// Regenerates the bundled snapshot of the IANA media type registry, for use in
// resource class editing.

import { appendFile, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";
import { parse } from "csv-parse/sync";

const REGISTRY_URL = "https://www.iana.org/assignments/media-types";

// For getting top-level types
const INDEX_URL = `${REGISTRY_URL}/media-types.xml`;
const INDEX_ID = "media-types";

// "example" is reserved by RFC 4735 for use in documentation, and nothing can
// be registered under it.
const UNREGISTERABLE_TOP_LEVEL_TYPES = new Set(["example"]);

// The top-level types RFC 2046 defined, which the registry will always hold.
const CORE_TOP_LEVEL_TYPES = [
  "application",
  "audio",
  "image",
  "message",
  "multipart",
  "text",
  "video",
];

const OUTPUT_PATH = fileURLToPath(
  new URL("../src/codex/ianaMediaTypes.json", import.meta.url),
);

// How many media types a report lists before deferring to the diff.
const LISTING_LIMIT = 50;

interface Snapshot {
  /** The date this snapshot's contents were taken, as an ISO date. */
  retrieved: string;
  source: string;
  mediaTypes: string[];
}

// For completeness, although we just use 'Template' which lists the actual type
interface RegistryRow {
  Name: string;
  Template: string;
  Reference: string;
}

/** The top-level types the registry currently publishes a registry for. */
async function fetchTopLevelTypes(): Promise<string[]> {
  const response = await fetch(INDEX_URL);
  if (!response.ok) {
    throw new Error(
      `Fetching the registry index failed: ${response.status} ${response.statusText}`,
    );
  }

  const index = await response.text();
  const ids = [...index.matchAll(/<registry\b[^>]*\bid="([^"]+)"/g)].map(
    (match) => match[1],
  );

  const missing = CORE_TOP_LEVEL_TYPES.filter((type) => !ids.includes(type));
  if (missing.length > 0) {
    throw new Error(
      `The registry index named no registry for ${missing.join(", ")}, so its format has probably changed`,
    );
  }

  return ids.filter(
    (id) => id !== INDEX_ID && !UNREGISTERABLE_TOP_LEVEL_TYPES.has(id),
  );
}

async function fetchRegistry(topLevelType: string): Promise<string[]> {
  const response = await fetch(`${REGISTRY_URL}/${topLevelType}.csv`);
  if (!response.ok) {
    throw new Error(
      `Fetching ${topLevelType}.csv failed: ${response.status} ${response.statusText}`,
    );
  }

  const rows: RegistryRow[] = parse(await response.text(), {
    columns: true,
    skipEmptyLines: true,
    trim: true,
  });

  const mediaTypes = rows
    .map((row) => row.Template)
    .filter((template) => template);

  for (const mediaType of mediaTypes) {
    if (!mediaType.startsWith(`${topLevelType}/`) || /\s/.test(mediaType)) {
      throw new Error(
        `${topLevelType}.csv has an unusable template: ${mediaType}`,
      );
    }
  }

  if (mediaTypes.length === 0) {
    throw new Error(`${topLevelType}.csv yielded no media types`);
  }

  return mediaTypes;
}

async function readSnapshot(): Promise<Snapshot | undefined> {
  try {
    return JSON.parse(await readFile(OUTPUT_PATH, "utf-8")) as Snapshot;
  } catch {
    // There is no snapshot yet, so everything the registry holds is new.
    return undefined;
  }
}

function without(mediaTypes: string[], others: string[]): string[] {
  const excluded = new Set(others);
  return mediaTypes.filter((mediaType) => !excluded.has(mediaType));
}

function topLevelTypeOf(mediaType: string): string {
  return mediaType.slice(0, mediaType.indexOf("/"));
}

/** A pull request body describing how the registry moved. */
function report(
  added: string[],
  removed: string[],
  newTopLevelTypes: string[],
): string {
  const lines = [
    "Regenerated by `npm run media-types:update`.",
    "",
    `- Added: ${added.length}`,
    `- Removed: ${removed.length}`,
    "",
    "Any removals should be scrutinized because IANA usually does not remove entries.",
  ];

  if (newTopLevelTypes.length > 0) {
    lines.push(
      "",
      `**New top-level ${newTopLevelTypes.length === 1 ? "type" : "types"}: ${newTopLevelTypes.join(", ")}.**`,
      "The media type tests assert which top-level types exist, so they need",
      "updating alongside this.",
    );
  }

  for (const [heading, mediaTypes] of [
    ["Added", added],
    ["Removed", removed],
  ] as const) {
    if (mediaTypes.length === 0) continue;

    lines.push(
      "",
      `### ${heading}`,
      "```",
      ...mediaTypes.slice(0, LISTING_LIMIT),
    );
    if (mediaTypes.length > LISTING_LIMIT) {
      lines.push("... see the diff for the rest");
    }
    lines.push("```");
  }

  return `${lines.join("\n")}\n`;
}

// Lets the workflow branch on whether there is anything to propose.
async function setGitHubOutput(name: string, value: string): Promise<void> {
  const outputPath = process.env.GITHUB_OUTPUT;
  if (!outputPath) return;

  await appendFile(outputPath, `${name}=${value}\n`);
}

const { values: options } = parseArgs({
  options: { report: { type: "string" } },
});

const topLevelTypes = await fetchTopLevelTypes();
const registries = await Promise.all(topLevelTypes.map(fetchRegistry));
const mediaTypes = [...new Set(registries.flat())].sort();

const previous = await readSnapshot();
const added = without(mediaTypes, previous?.mediaTypes ?? []);
const removed = without(previous?.mediaTypes ?? [], mediaTypes);
const changed = added.length > 0 || removed.length > 0;

const knownTopLevelTypes = new Set(
  (previous?.mediaTypes ?? []).map(topLevelTypeOf),
);
const newTopLevelTypes = [...new Set(added.map(topLevelTypeOf))].filter(
  (topLevelType) => !knownTopLevelTypes.has(topLevelType),
);

if (changed) {
  const snapshot: Snapshot = {
    retrieved: new Date().toISOString().slice(0, 10),
    source: `${REGISTRY_URL}/media-types.xhtml`,
    mediaTypes,
  };

  await writeFile(OUTPUT_PATH, `${JSON.stringify(snapshot, null, 2)}\n`);

  console.log(
    `Wrote ${mediaTypes.length} media types to ${OUTPUT_PATH} (${added.length} added, ${removed.length} removed)`,
  );

  if (options.report) {
    await writeFile(options.report, report(added, removed, newTopLevelTypes));
  }
} else {
  console.log(
    `The registry still holds the same ${mediaTypes.length} media types; leaving the snapshot alone.`,
  );
}

await setGitHubOutput("changed", String(changed));
